### ISSUE TITLE
Improve input encoding handling 

### ISSUE THREAD

**Issue by NTBBloodbath** [neo-sh/neosh#36]
Right now neosh dies if someone inserts cyrillic characters, russian characters, etc that aren't part of LATIN1 encoding.

This is not an expected behavior, and we could use some crates like [encoding.rs](https://lib.rs/crates/encoding_rs) to deal with these characters.

**Comment by LordMZTE** [comment]
I'm not sure the right solution here is to try to understand the encoding. If we could treat the user input as plain bytes, that would not only lift the unecessary UTF-8 restriction and thus make the shell more flexible, but also rule out a whole class of bugs.

We could look into the [bstr](https://lib.rs/crates/bstr) crate, which provides string-like methods on bytes if needed.
